config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links

  get ":key" => "links#forward", as: :link_redirect

  get "/" => "links#new", as: :root

  namespace :api, defaults: { format: "json" } do
    namespace :v1 do
      scope(controller: :links_api) do
        post "short_url" => "links_api#generate_short_url"
        post "stats" => "links_api#get_statistics"
      end
    end
  end
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :user_url_visits
  has_many :users, through: :user_url_visits

  BASE_URL = "http://pte.ly"

  def self.generate_key
    (("0".."9").to_a + ("A".."Z").to_a + ("a".."z").to_a).shuffle.first(6).join
  end

  def generate_short_url
    [BASE_URL, self.key].join("/")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_url_visits
  has_many :links, through: :user_url_visits
end

app/models/user_url_visit.rb
class UserUrlVisit < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ApplicationController
  API_TOKEN = "da0feda374beb6b3c2dde5e71e68888e"

  skip_before_filter :verify_authenticity_token
  skip_before_filter :authenticate_user!

  before_action :authenticate_api_request

  private
    def authenticate_api_request
      authenticate_or_request_with_http_token do |token, options|
        token == API_TOKEN
      end
    end
end

app/controllers/api/v1/links_api_controller.rb
class Api::V1::LinksApiController < Api::V1::BaseController
  def generate_short_url
    render json: { errors: "Missing required parameter URL" }, status: 400 and return if params[:url].blank?
    render json: { errors: "Shortened URL is already present for the given url" }, status: 400 and return if Link.find_by(actual_url: params[:url]).present?

    @link = Link.new(actual_url: params[:url])
    @link.key = Link.generate_key
    @link.short_url = @link.generate_short_url
    if @link.save
      render json: { short_url: @link.short_url }, status: 200
    else
      render json: { errors: @link.errors.full_messages.to_sentence }, status: 422
    end
  end

  def get_statistics
    render json: { errors: "Missing required parameter URL" }, status: 400 and return if params[:url].blank?
    render json: { errors: "Could not find the link" }, status: 422 and return unless @link = Link.find_by(short_url: params[:url])

    @stats = []
    UserUrlVisit.where(link_id: @link).group_by(&:user_id).map { |user_id, visits|
      user = User.find user_id
      @stats << {
        email: user.email,
        ip_address: user.last_sign_in_ip.to_s,
        visit_count: visits.count,
        last_visited_at: visits.last.created_at.strftime("%d %b, %H:%M %P")
      }
    }

    render json: { user_stats: @stats }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all.reverse_order
  end

  def new
    @link = Link.new
    @top_links = Link.all.order("clicks DESC").first(5)
  end

  def create
    if params[:link][:actual_url].blank?
      flash[:error] = "Enter a URL to shorten it"
      redirect_to new_link_path and return
    end
    if @link = Link.find_by(actual_url: params[:link][:actual_url])
      flash[:error] = "Short URL already present for the given url #{@link.short_url}".html_safe
      redirect_to new_link_path and return
    end

    @link = Link.new link_params
    @link.key = Link.generate_key
    @link.short_url = @link.generate_short_url
    if @link.save
      flash[:success] = "Shortened Link successfully created"
      redirect_to links_path
    else
      flash[:error] = @link.errors.full_messages.to_sentence
    end
  end

  def forward
    @link = Link.find_by key: params[:key]
    if @link
      @link.clicks += 1
      @link.save

      current_user.links << @link
      redirect_to @link.actual_url
    end
  end

  private
    def link_params
      params.require(:link).permit(:actual_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkShortnerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li><%= link_to "All Links", links_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a><%= "Logged in as #{current_user.email}" if current_user %></a></li>
        </ul>
    </div>
  </nav>

  <div class="container">
    <% if flash[:success].present? %>
      <div class="alert alert-success"><%= flash[:success] %></div>
    <% end %>
    <% if flash[:error].present? %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>
    <% if flash[:notice].present? %>
      <div class="alert alert-info"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/links/index.html.erb
<% @links.each do |l| %>
  <ul class="list-group">
    <li class="list-group-item">
      <span class="badge"><%= l.clicks %> clicks</span>
      <%= l.actual_url %><br />
      <%= link_to l.short_url, link_redirect_path(l.key), target: "_blank" %>
    </li>
  </ul>
<% end %>

app/views/links/new.html.erb
<%= form_for @link, class: "form-horizontal" do |l| %>
  <div class="form-group form-group-lg">
    <div class="row">
      <div class="col-md-8">
        <%= l.text_field :actual_url, class: "form-control", placeholder: "Enter a URL to shorten" %>
      </div>
      <div class="col-md-3">
        <%= l.submit "Shorten", class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
<% end %>

<div class="page-header">
  <h2>Top 5 links</h2>
</div>

<% @top_links.each do |l| %>
  <ul class="list-group">
    <li class="list-group-item">
      <span class="badge"><%= l.clicks %> clicks</span>
      <%= l.actual_url %><br />
      <%= link_to l.short_url, link_redirect_path(l.key), target: "_blank" %>
    </li>
  </ul>
<% end %>